#!/bin/bash
DIR="$( cd "$( dirname $0 )" && pwd )"
SCRIPTPATH=$DIR/ZNonPublicDeps
OJDBCDIR=ojdbc7
# I know. Play nicely, This is to make PRBuilds from other repos work
export CxD=$(echo wraan | tr '[A-Za-z]' '[N-ZA-Mn-za-m]')
openssl enc -in ${SCRIPTPATH}/mssql.enc -out ./sqljdbc42.jar -d -aes256  -pass env:CxD
openssl enc -in ${SCRIPTPATH}/npj.enc -out ${SCRIPTPATH}/npj.tjz -d -aes256  -pass env:CxD
tar xvjf ${SCRIPTPATH}/npj.tjz -C ${SCRIPTPATH}
cp ${SCRIPTPATH}/nonpublicjars/${OJDBCDIR}/jars/ojdbc7-12.1.0.2.jar .
